lint with shfmt

diff --git a/tag-git/bin/git-c b/tag-git/bin/git-c
--- a/tag-git/bin/git-c
+++ b/tag-git/bin/git-c
@@ -5,8 +5,8 @@
 GITHUB_USERNAME=astrophena
 
 if [ -z "$1" ]; then
-  echo 'repo name is required'
-  exit 1
+	echo 'repo name is required'
+	exit 1
 fi
 
 git clone "https://github.com/${GITHUB_USERNAME}/$1"
